// global to handle editor state
enum EditorMode
{
    EDITOR_MODE_SELECT_POLY,
    EDITOR_MODE_ADD_POLY,
    EDITOR_MODE_MODIFY_POLY,
    EDITOR_MODE_MOVE_3D_CAMERA,
    EDITOR_MODE_SET_TEXTURE,
    EDITOR_MODE_CLIPPING,

    EDITOR_MODE_COUNT
};

enum ControlPoint
{
    CONTROL_POINT_BOTL,
    CONTROL_POINT_BOTR,
    CONTROL_POINT_TOPL,
    CONTROL_POINT_TOPR,
    CONTROL_POINT_MIDL,
    CONTROL_POINT_MIDR,
    CONTROL_POINT_MIDT,
    CONTROL_POINT_MIDB,

    CONTROL_POINT_COUNT
};
